version: "3.8"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Password@123
      MYSQL_DATABASE: stock_market
      MYSQL_USER: jay
      MYSQL_PASSWORD: jay

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+mysqlconnector://jay:jay@db/stock_market
